### ISSUE TITLE
add custom fonts

### ISSUE THREAD

**Issue by ramboz** [hlxsites/delta#4]
Include the custom fonts from delta.com in the `lazy-styles.css`

You can get those from https://www.delta.com/content/dam/delta-applications/fresh-air-core/22.7.0/fonts/fresh-air-fonts.css

**Comment by cgoudie** [comment]
I uploaded the fonts here: https://github.com/hlxsites/delta/tree/main/styles/fonts

in the event there's another CSS with fonts, the command I used is this:
`wget --user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36" -O - "https://www.delta.com/content/dam/delta-applications/fresh-air-core/22.7.0/fonts/fresh-air-fonts.css" | tr ' ' '\n' | grep url | cut -d \" -f 4 | sed -e 's/\.\///g' | while read in; do wget --user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36" [https://www.delta.com/content/dam/delta-applications/fresh-air-core/22.7.0/fonts/${in}](https://www.delta.com/content/dam/delta-applications/fresh-air-core/22.7.0/fonts/$%7Bin%7D); done`

I'm realizing now that I pushed the change directly to main, but they most probably need a git-mv to the correct location. Hope this helps unlock you @asthabh23
