### ISSUE TITLE
Add support for complex accordion block with embeds

### ISSUE THREAD

**Issue by ramboz** [hlxsites/delta#85]
some pages are using accordions with an embedded table.

The proposal is to extract each accordion content into a separate page. The accordion content would be a simple link to the `.plain.html`, and the accordion block would dynamically load this async as needed.

List:
- [x] https://www.delta.com/us/en/skymiles/medallion-program/international-partner-skyteam-benefits
- [x] https://www.delta.com/us/en/skymiles/medallion-program/medallion-upgrades
- [ ] https://www.delta.com/us/en/skymiles/program-resources/program-rules

**Comment by Dereje24** [comment]
Adding a page here: https://www.delta.com/us/en/skymiles/program-resources/program-rules
